global:
  name: consul
  datacenter: dc1
  image: consul:1.9.0-beta1

server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0

client:
  enabled: true
  grpc: true

ui:
  enabled: true

connectInject:
  enabled: true
  default: true
controller:
  enabled: true