---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: test-route-1
spec:
  parentRefs:
  - name: test-gateway
  rules:
  - matches:
    - path:
        type: RegularExpression
        value: ^/echo.*
    backendRefs:
    - kind: Service
      name: echo-1
      port: 8080
      weight: 50
    - kind: Service
      name: echo-2
      port: 8090
      weight: 50
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: test-route-2
spec:
  parentRefs:
  - name: test-gateway
  rules:
  - matches:
    - path:
        type: RegularExpression
        value: ^/.*
    backendRefs:
    - kind: Service
      name: frontend
      port: 80