global:
  name: consul
  datacenter: dc1
  image: consul:1.9.0-beta1
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    enabled: true
    maxUnavailable: 0
  extraConfig: |
    {
      "ui_config": {
        "enabled": true,
        "metrics_provider": "prometheus",
        "metrics_proxy": {
          "base_url": "http://prometheus-server"
        }
      }
    }
client:
  enabled: true
  grpc: true
ui:
  enabled: true
connectInject:
  enabled: true
  default: true
  centralConfig:
    enabled: true
controller:
  enabled: true