global:
  name: consul
  datacenter: dc1
  image: hashicorp/consul:1.10.1
  imageEnvoy: envoyproxy/envoy:v1.18.3
  imageK8S: hashicorp/consul:0.26.0
  metrics:
    enabled: true
    enableAgentMetrics: true
server:
  replicas: 1
ui:
  enabled: true
connectInject:
  enabled: true
  default: true
controller:
  enabled: true
prometheus:
  enabled: true
grafana:
  enabled: true
