apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default
spec:
  services:
#  - name: mesh-gateway
#    namespace: default
#    consumers:
#    - partition: tereknor
  - name: postgres
    namespace: default
    consumers:
    - partition: tereknor
