apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: tereknor
spec:
  services:
#  - name: mesh-gateway
#    namespace: default
#    consumers:
#    - partition: default
  - name: product-api
    namespace: default
    consumers:
    - partition: default
